# -*- coding: utf-8 -*-
"""Code for Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U4qMKG2BjJv1FHeAazfaAiZabN1kp8lw
"""

# ============================================================
# END-TO-END MACHINE LEARNING PIPELINE FOR LOAN DEFAULT ANALYSIS
# Techniques: Data Preprocessing, SMOTE Balancing, Model Training
# Algorithms: Logistic Regression, Random Forest, XGBoost, PyTorch
# Evaluation: Accuracy, Confusion Matrix, Classification Report
# ============================================================

# ===================== IMPORT LIBRARIES =====================

# Data Handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt

# Sklearn - Preprocessing & Model Evaluation
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Machine Learning Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Handling Imbalanced Data
from imblearn.over_sampling import SMOTE

# Deep Learning (Neural Networks)
import torch
import torch.nn as nn
import torch.optim as optim

# ===================== LOAD DATASET =====================

# Read the CSV file into a DataFrame
# This loads your dataset into memory so you can work with it
df = pd.read_csv("loan_default_dataset.csv")


# Print the shape of the dataset
# Shape = (rows, columns)
# Example: (5000, 12) → 5000 records and 12 features
print("Shape:", df.shape)


# Display first 5 rows of the dataset
# Helps to quickly understand data structure and values
print(df.head())

# ===================== DATA PREPROCESSING =====================

# Fill missing values with mean (only for numeric columns)
# This replaces NaN values with the average of each column
df.fillna(df.mean(numeric_only=True), inplace=True)


# Encode categorical columns (convert text → numbers)
# Example: "Male" → 0, "Female" → 1
le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])


# Split dataset into Features (X) and Target (y)
# "Default" is what we want to predict
X = df.drop("Default", axis=1)
y = df["Default"]


# Split data into Training (80%) and Testing (20%)
# Training data → used to train model
# Testing data → used to evaluate model
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# ===================== HANDLE IMBALANCED DATA =====================

# Apply SMOTE (Synthetic Minority Oversampling Technique)
# It creates synthetic samples for minority class (Default = 1)
# So both classes become balanced
sm = SMOTE(random_state=42)
X_train, y_train = sm.fit_resample(X_train, y_train)

# Print class distribution after SMOTE
# Example: [900, 900] → balanced dataset
print("After SMOTE:", np.bincount(y_train))


# ===================== FEATURE SCALING =====================

# Standardize features (mean = 0, std = 1)
# Important for models like Logistic Regression, Neural Networks
scaler = StandardScaler()

# Fit on training data and transform
X_train = scaler.fit_transform(X_train)

# Only transform test data (no fitting to avoid data leakage)
X_test = scaler.transform(X_test)

# ===================== MODEL TRAINING & EVALUATION =====================

# Define multiple ML models in a dictionary
# Key = Model name, Value = Model object
models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Dictionary to store accuracy results of each model
results = {}

# Loop through each model
for name, model in models.items():

    # Train the model using training data
    model.fit(X_train, y_train)

    # Make predictions on test data
    preds = model.predict(X_test)

    # Calculate accuracy (how many predictions are correct)
    acc = accuracy_score(y_test, preds)

    # Store accuracy in results dictionary
    results[name] = acc

    # Print model name
    print(f"\n{name}")

    # Print accuracy score
    print("Accuracy:", acc)

    # Print confusion matrix
    # Shows: True Positive, True Negative, False Positive, False Negative
    print(confusion_matrix(y_test, preds))

    # Print detailed classification report
    # Includes Precision, Recall, F1-score
    print(classification_report(y_test, preds))

# ===================== NEURAL NETWORK (MLP MODEL) =====================

# Define a Multi-Layer Perceptron (MLP) class
class MLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        # Define network layers
        # Input → 32 neurons → 16 neurons → Output (2 classes)
        self.model = nn.Sequential(
            nn.Linear(input_dim, 32),  # Input layer to hidden layer
            nn.ReLU(),                 # Activation function
            nn.Linear(32, 16),         # Hidden layer
            nn.ReLU(),                 # Activation function
            nn.Linear(16, 2)           # Output layer (2 classes: Default / No Default)
        )

    # Forward pass (how data flows through network)
    def forward(self, x):
        return self.model(x)


# Create model instance
mlp = MLP(X_train.shape[1])  # input_dim = number of features


# ===================== LOSS & OPTIMIZER =====================

# Loss function (used for classification problems)
criterion = nn.CrossEntropyLoss()

# Optimizer (updates model weights to reduce loss)
optimizer = optim.Adam(mlp.parameters(), lr=0.001)


# ===================== CONVERT DATA TO TENSORS =====================

# Convert training data to PyTorch tensors
X_train_tensor = torch.FloatTensor(X_train)
y_train_tensor = torch.LongTensor(y_train.values)


# ===================== TRAINING LOOP =====================

# Train model for 50 epochs (iterations)
for epoch in range(50):

    # Clear previous gradients
    optimizer.zero_grad()

    # Forward pass → get predictions
    outputs = mlp(X_train_tensor)

    # Calculate loss (difference between prediction & actual)
    loss = criterion(outputs, y_train_tensor)

    # Backpropagation → compute gradients
    loss.backward()

    # Update weights
    optimizer.step()

    # Print loss every 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# ===================== AUTOENCODER MODEL =====================

# Define Autoencoder class
class Autoencoder(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        # Encoder: compresses input data → lower dimension (feature extraction)
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 16),  # Input → 16 neurons
            nn.ReLU(),                 # Activation
            nn.Linear(16, 8)           # 16 → 8 (compressed representation)
        )

        # Decoder: reconstructs original data from compressed form
        self.decoder = nn.Sequential(
            nn.Linear(8, 16),          # 8 → 16
            nn.ReLU(),                 # Activation
            nn.Linear(16, input_dim)   # Back to original input size
        )

    # Forward pass
    def forward(self, x):
        z = self.encoder(x)     # Encode input (compression)
        return self.decoder(z)  # Decode (reconstruction)


# Create Autoencoder model
ae = Autoencoder(X_train.shape[1])


# ===================== LOSS & OPTIMIZER =====================

# Optimizer (updates weights)
optimizer = optim.Adam(ae.parameters(), lr=0.001)

# Loss function (measures reconstruction error)
# MSE = difference between original input and reconstructed output
criterion = nn.MSELoss()


# ===================== TRAINING LOOP =====================

for epoch in range(50):

    # Clear previous gradients
    optimizer.zero_grad()

    # Forward pass → reconstruct input data
    recon = ae(X_train_tensor)

    # Compute reconstruction loss
    loss = criterion(recon, X_train_tensor)

    # Backpropagation
    loss.backward()

    # Update weights
    optimizer.step()

    # (Optional) print loss every 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# ===================== AUTOENCODER MODEL =====================

# Define Autoencoder class
class Autoencoder(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        # Encoder: compresses input data → lower dimension (feature extraction)
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 16),  # Input → 16 neurons
            nn.ReLU(),                 # Activation
            nn.Linear(16, 8)           # 16 → 8 (compressed representation)
        )

        # Decoder: reconstructs original data from compressed form
        self.decoder = nn.Sequential(
            nn.Linear(8, 16),          # 8 → 16
            nn.ReLU(),                 # Activation
            nn.Linear(16, input_dim)   # Back to original input size
        )

    # Forward pass
    def forward(self, x):
        z = self.encoder(x)     # Encode input (compression)
        return self.decoder(z)  # Decode (reconstruction)


# Create Autoencoder model
ae = Autoencoder(X_train.shape[1])


# ===================== LOSS & OPTIMIZER =====================

# Optimizer (updates weights)
optimizer = optim.Adam(ae.parameters(), lr=0.001)

# Loss function (measures reconstruction error)
# MSE = difference between original input and reconstructed output
criterion = nn.MSELoss()


# ===================== TRAINING LOOP =====================

for epoch in range(50):

    # Clear previous gradients
    optimizer.zero_grad()

    # Forward pass → reconstruct input data
    recon = ae(X_train_tensor)

    # Compute reconstruction loss
    loss = criterion(recon, X_train_tensor)

    # Backpropagation
    loss.backward()

    # Update weights
    optimizer.step()

    # (Optional) print loss every 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# ===================== COUNTERFACTUAL GENERATION =====================

# Select one sample from test data
# This is the original input for which we want explanation
sample = X_test[0]


# Generate counterfactual example
# Counterfactual = "What minimal changes are needed to change prediction?"
# Example: increase income → loan might not default
cf = generate_counterfactual(sample, mlp)


# Print original sample values
print("\nOriginal:", sample)

# Print counterfactual values (modified version of input)
print("\nCounterfactual:", cf)

# ===================== CAUSAL ANALYSIS (ATE & ITE) =====================

# Define Treatment and Outcome
# Treatment = feature we want to study (Credit Amount)
# Outcome = result we care about (Default or Not)
treatment = df["Credit_Amount"]
outcome = df["Default"]


# Create a threshold using median value
# This splits data into "High Credit" and "Low Credit"
threshold = treatment.median()


# Divide data into two groups:
# Treated group → Credit_Amount > median
# Control group → Credit_Amount <= median
treated = outcome[treatment > threshold]
control = outcome[treatment <= threshold]


# ===================== ATE (Average Treatment Effect) =====================

# ATE = average difference between treated and control groups
# Shows overall effect of high credit amount on default
ATE = treated.mean() - control.mean()
print("ATE:", ATE)


# ===================== ITE (Individual Treatment Effect) =====================

# ITE = difference at individual level (approximation here)
# Compare individual outcomes between groups
ITE = treated.values[:len(control)] - control.values

# Print first 10 ITE values
print("Sample ITE:", ITE[:10])

# ===================== CONFUSION MATRIX VISUALIZATION =====================

# Import seaborn for better visualization
import seaborn as sns


# Select the trained XGBoost model
model = models["XGBoost"]


# Make predictions on test data
preds = model.predict(X_test)


# Compute confusion matrix
# It shows:
# [ True Negative   False Positive ]
# [ False Negative  True Positive ]
cm = confusion_matrix(y_test, preds)


# Create a heatmap (visual representation of confusion matrix)
plt.figure()

# annot=True → shows numbers inside boxes
# fmt="d" → display numbers as integers
sns.heatmap(cm, annot=True, fmt="d")

# Add title to the plot
plt.title("Confusion Matrix")

# Display the plot
plt.show()

# ===================== FEATURE IMPORTANCE VISUALIZATION =====================

# Get feature importance scores from trained model (XGBoost)
# Importance = how much each feature contributes to prediction
importances = model.feature_importances_


# Create a bar chart to visualize feature importance
plt.figure()

# range(len(importances)) → positions of bars (one for each feature)
# importances → height of each bar (importance value)
plt.bar(range(len(importances)), importances)


# Add title to the plot
plt.title("Feature Importance")


# Show the plot
plt.show()