# -*- coding:2 -*-
"""New Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GpJxFk-tre7X-q8z9L3BMFf84_xLRqB
"""

# ============================================
# PROCE Counterfactual Explanation Pipeline
# With Graphs
# Using german_processed.csv
# ============================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import random
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import NearestNeighbors

# ============================================
# 1 Load Dataset
# ============================================

df = pd.read_csv("german_processed.csv")

y = df["GoodCustomer"]
X = df.drop("GoodCustomer", axis=1)

X = pd.get_dummies(X)

# ============================================
# 2 Train/Test Split
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ============================================
# 3 Feature Scaling
# ============================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ============================================
# 4 Train Classifier
# ============================================

model = MLPClassifier(hidden_layer_sizes=(64,32),
                      max_iter=500,
                      random_state=42)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

# Confusion Matrix Graph
cm = confusion_matrix(y_test, pred)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.colorbar()
plt.show()

# ============================================
# 5 Autoencoder Model
# ============================================

input_dim = X_train.shape[1]
latent_dim = 10

class AutoEncoder(nn.Module):

    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Linear(input_dim,32),
            nn.ReLU(),
            nn.Linear(32,latent_dim)
        )

        self.decoder = nn.Sequential(
            nn.Linear(latent_dim,32),
            nn.ReLU(),
            nn.Linear(32,input_dim)
        )

    def forward(self,x):

        z = self.encoder(x)
        x_recon = self.decoder(z)

        return x_recon

ae = AutoEncoder()

criterion = nn.MSELoss()
optimizer = optim.Adam(ae.parameters(),lr=0.001)

X_tensor = torch.tensor(X_train,dtype=torch.float32)

loss_history = []

# ============================================
# 6 Train Autoencoder
# ============================================

for epoch in range(100):

    optimizer.zero_grad()

    recon = ae(X_tensor)

    loss = criterion(recon,X_tensor)

    loss.backward()

    optimizer.step()

    loss_history.append(loss.item())

# Loss Graph
plt.figure()
plt.plot(loss_history)
plt.xlabel("Epoch")
plt.ylabel("Reconstruction Loss")
plt.title("Autoencoder Training Loss")
plt.show()

# ============================================
# 7 Prototype Creation
# ============================================

x_org = X_test[0].reshape(1,-1)

y_org = model.predict(x_org)[0]

y_cf = -1 if y_org==1 else 1

X_train_cf = X_train[y_train==y_cf]

nbrs = NearestNeighbors(n_neighbors=10)

nbrs.fit(X_train_cf)

distances,indices = nbrs.kneighbors(x_org)

neighbors = X_train_cf[indices[0]]

with torch.no_grad():

    latent_neighbors = ae.encoder(
        torch.tensor(neighbors,dtype=torch.float32)
    )

prototype = torch.mean(latent_neighbors,dim=0)

# ============================================
# 8 Genetic Algorithm Counterfactual Search
# ============================================

population_size = 50
generations = 50
mutation_rate = 0.1

population = np.random.normal(0,1,
            (population_size,X_train.shape[1]))

def prediction_loss(x):

    prob = model.predict_proba(x.reshape(1,-1))[0]

    if y_cf==1:
        return -np.log(prob[1]+1e-6)
    else:
        return -np.log(prob[0]+1e-6)

def prototype_loss(x):

    with torch.no_grad():

        z = ae.encoder(
            torch.tensor(x,dtype=torch.float32)
        )

    return torch.norm(z-prototype).item()

def distance_loss(x):

    return np.linalg.norm(x-x_org)

def fitness(x):

    return prediction_loss(x)+prototype_loss(x)+distance_loss(x)

loss_curve = []

for g in range(generations):

    scores = np.array([fitness(ind) for ind in population])

    loss_curve.append(scores.min())

    best_idx = np.argsort(scores)[:population_size//2]

    survivors = population[best_idx]

    children = []

    while len(children)<population_size:

        p1,p2 = random.sample(list(survivors),2)

        child=(p1+p2)/2

        if random.random()<mutation_rate:

            child += np.random.normal(0,0.1,len(child))

        children.append(child)

    population = np.array(children)

# Convergence Graph
plt.figure()
plt.plot(loss_curve)
plt.xlabel("Generation")
plt.ylabel("Best Loss")
plt.title("Counterfactual Search Convergence")
plt.show()

# ============================================
# 9 Best Counterfactual
# ============================================

scores = np.array([fitness(ind) for ind in population])

best = population[np.argmin(scores)]

print("Original Prediction:",y_org)

print("Counterfactual Prediction:",
      model.predict(best.reshape(1,-1))[0])

# ============================================
# 10 Feature Change Graph
# ============================================

change = best - x_org

plt.figure()
plt.bar(range(len(change[0])),change[0])
plt.xlabel("Feature Index")
plt.ylabel("Change Value")
plt.title("Feature Changes for Counterfactual")
plt.show()
