# -*- coding: 7 -*-
"""project code modified.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyzJYrc25WJZs6Ujw0zUNJTsTMlHdB1Z
"""

# ============================================================
# END-TO-END MACHINE LEARNING PIPELINE FOR LOAN DEFAULT ANALYSIS
# Techniques: Data Preprocessing, SMOTE Balancing, Model Training
# Algorithms: Logistic Regression, Random Forest, XGBoost, PyTorch
# Evaluation: Accuracy, Confusion Matrix, Classification Report
# ============================================================

# Brief Description:
# This code sets up a complete machine learning pipeline for predicting loan default.
# It includes data handling (pandas, numpy), visualization (matplotlib),
# preprocessing (label encoding, feature scaling), and data splitting.
# SMOTE is used to handle class imbalance in the dataset.
# Multiple models are imported for comparison: Logistic Regression,
# Random Forest, XGBoost, and a deep learning model using PyTorch.
# Model performance is evaluated using accuracy, confusion matrix,
# and classification report.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE

import torch
import torch.nn as nn
import torch.optim as optim

df = pd.read_csv("loan_default_dataset.csv")

print("Shape:", df.shape)
print(df.head())

# Fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# Encode categorical columns
le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

# Features & Target
X = df.drop("Default", axis=1)
y = df["Default"]

# Train-Test Split (Stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Apply SMOTE to handle class imbalance in the training dataset
sm = SMOTE(random_state=42)

# fit_resample() creates synthetic samples for the minority class
# so that both classes become balanced
X_train, y_train = sm.fit_resample(X_train, y_train)

# Display the number of samples in each class after applying SMOTE
# np.bincount() counts occurrences of each class label (e.g., 0 and 1)
print("After SMOTE:", np.bincount(y_train))

# Create a StandardScaler object (used to normalize data)
scaler = StandardScaler()

# Fit on training data (learn mean & std) and transform it
# This makes data have mean = 0 and standard deviation = 1
X_train = scaler.fit_transform(X_train)

# Transform test data using same values learned from training data
# (important to avoid data leakage)
X_test = scaler.transform(X_test)

from sklearn.ensemble import GradientBoostingClassifier

# Define multiple machine learning models for comparison
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),  # Simple baseline model
    "Random Forest": RandomForestClassifier(),                 # Uses multiple decision trees
    "Gradient Boosting": GradientBoostingClassifier(),         # Improves model step-by-step
    "XGBoost": XGBClassifier(eval_metric='logloss')            # Advanced boosting algorithm
}

# Dictionary to store accuracy of each model
results = {}

# Loop through each model
for name, model in models.items():

    # Train the model using training data
    model.fit(X_train, y_train)

    # Make predictions on test data
    preds = model.predict(X_test)

    # Calculate accuracy (how many predictions are correct)
    acc = accuracy_score(y_test, preds)

    # Store accuracy result
    results[name] = acc

    # Print model name
    print(f"\n{name}")

    # Print accuracy score
    print("Accuracy:", acc)

    # Print confusion matrix (shows correct & incorrect predictions)
    print(confusion_matrix(y_test, preds))

    # Print detailed report (precision, recall, F1-score)
    print(classification_report(y_test, preds))

# ===================== MODEL TRAINING =====================

models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

results = {}

for name, model in models.items():

    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    acc = accuracy_score(y_test, preds)
    results[name] = acc

    print(f"\n{name}")
    print("Accuracy:", acc)
    print(confusion_matrix(y_test, preds))
    print(classification_report(y_test, preds))

# ===================== NEURAL NETWORK (MLP MODEL) =====================

# Define a Multi-Layer Perceptron (MLP) class
class MLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        # Define network layers
        # Input → 32 neurons → 16 neurons → Output (2 classes)
        self.model = nn.Sequential(
            nn.Linear(input_dim, 32),  # Input layer to hidden layer
            nn.ReLU(),                 # Activation function
            nn.Linear(32, 16),         # Hidden layer
            nn.ReLU(),                 # Activation function
            nn.Linear(16, 2)           # Output layer (2 classes: Default / No Default)
        )

    # Forward pass (how data flows through network)
    def forward(self, x):
        return self.model(x)


# Create model instance
mlp = MLP(X_train.shape[1])  # input_dim = number of features


# ===================== LOSS & OPTIMIZER =====================

# Loss function (used for classification problems)
criterion = nn.CrossEntropyLoss()

# Optimizer (updates model weights to reduce loss)
optimizer = optim.Adam(mlp.parameters(), lr=0.001)


# ===================== CONVERT DATA TO TENSORS =====================

# Convert training data to PyTorch tensors
X_train_tensor = torch.FloatTensor(X_train)
y_train_tensor = torch.LongTensor(y_train.values)


# ===================== TRAINING LOOP =====================

# Train model for 50 epochs (iterations)
for epoch in range(50):

    # Clear previous gradients
    optimizer.zero_grad()

    # Forward pass → get predictions
    outputs = mlp(X_train_tensor)

    # Calculate loss (difference between prediction & actual)
    loss = criterion(outputs, y_train_tensor)

    # Backpropagation → compute gradients
    loss.backward()

    # Update weights
    optimizer.step()

    # Print loss every 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

class Autoencoder(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        # Encoder: reduces input data into a smaller representation (compression)
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 16),  # Input → 16 neurons
            nn.ReLU(),                 # Activation function
            nn.Linear(16, 8)           # 16 → 8 (compressed form)
        )

        # Decoder: reconstructs original data from compressed representation
        self.decoder = nn.Sequential(
            nn.Linear(8, 16),          # 8 → 16 neurons
            nn.ReLU(),                 # Activation function
            nn.Linear(16, input_dim)   # Back to original input size
        )

    def forward(self, x):
        # Pass input through encoder to get compressed features
        z = self.encoder(x)

        # Pass compressed features through decoder to reconstruct input
        return self.decoder(z)

class Autoencoder(nn.Module):
    def __init__(self, input_dim):
        super().__init__()  # Initialize parent class (PyTorch module)

        # Encoder: compresses input data into a smaller representation
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 16),  # Convert input → 16 features
            nn.ReLU(),                 # Add non-linearity
            nn.Linear(16, 8)           # Reduce to 8 features (compressed data)
        )

        # Decoder: reconstructs original data from compressed form
        self.decoder = nn.Sequential(
            nn.Linear(8, 16),          # Expand 8 → 16
            nn.ReLU(),                 # Activation
            nn.Linear(16, input_dim)   # Restore to original input size
        )

    def forward(self, x):
        # Encode input into compressed representation
        z = self.encoder(x)

        # Decode compressed data back to original form
        return self.decoder(z)

# ===================== DEFINE TREATMENT & OUTCOME =====================
# Treatment variable: Credit Amount (input factor)
treatment = df["Credit_Amount"]

# Outcome variable: Default (target result: 0 or 1)
outcome = df["Default"]


# ===================== CREATE THRESHOLD =====================
# Use median to divide data into two groups
threshold = treatment.median()


# ===================== CREATE TREATED & CONTROL GROUPS =====================
# Treated group: higher credit amount than median
treated = outcome[treatment > threshold]

# Control group: lower or equal credit amount
control = outcome[treatment <= threshold]


# ===================== CALCULATE ATE (Average Treatment Effect) =====================
# Difference in average outcome between treated and control groups
ATE = treated.mean() - control.mean()

print("ATE:", ATE)


# ===================== CALCULATE ITE (Individual Treatment Effect - Approx) =====================
# Difference between individual treated and control values (approximation)
ITE = treated.values[:len(control)] - control.values

print("Sample ITE:", ITE[:10])  # Show first 10 values

# ===================== CONFUSION MATRIX VISUALIZATION =====================

# Import seaborn for better visualization
import seaborn as sns


# Select the trained XGBoost model
model = models["XGBoost"]


# Make predictions on test data
preds = model.predict(X_test)


# Compute confusion matrix
# It shows:
# [ True Negative   False Positive ]
# [ False Negative  True Positive ]
cm = confusion_matrix(y_test, preds)


# Create a heatmap (visual representation of confusion matrix)
plt.figure()

# annot=True → shows numbers inside boxes
# fmt="d" → display numbers as integers
sns.heatmap(cm, annot=True, fmt="d")

# Add title to the plot
plt.title("Confusion Matrix")

# Display the plot
plt.show()

# ===================== FEATURE IMPORTANCE VISUALIZATION =====================

# Get feature importance scores from trained model (XGBoost)
# Importance = how much each feature contributes to prediction
importances = model.feature_importances_


# Create a bar chart to visualize feature importance
plt.figure()

# range(len(importances)) → positions of bars (one for each feature)
# importances → height of each bar (importance value)
plt.bar(range(len(importances)), importances)


# Add title to the plot
plt.title("Feature Importance")


# Show the plot
plt.show()
