# -*- coding: utf-3 -*-
"""Test Germany.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6khb-FuVK7RX4pT1xBxRoA7RHDSlo9a
"""

# ============================================
# FINAL PROCE COUNTERFACTUAL PIPELINE (TEST)
# ============================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import random
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import NearestNeighbors

# ============================================
# 1 LOAD DATA
# ============================================

df = pd.read_csv("german_processed.csv")

y = df["GoodCustomer"]
X = df.drop("GoodCustomer", axis=1)

X = pd.get_dummies(X)

# ============================================
# 2 SPLIT
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ============================================
# 3 SCALING
# ============================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ============================================
# 4 CLASSIFIER
# ============================================

model = MLPClassifier(hidden_layer_sizes=(64,32),
                      max_iter=500,
                      random_state=42)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

# Confusion Matrix
cm = confusion_matrix(y_test, pred)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.colorbar()
plt.show()

# ============================================
# 5 AUTOENCODER
# ============================================

input_dim = X_train.shape[1]
latent_dim = 10

class AutoEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim,32),
            nn.ReLU(),
            nn.Linear(32,latent_dim)
        )
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim,32),
            nn.ReLU(),
            nn.Linear(32,input_dim)
        )

    def forward(self,x):
        z = self.encoder(x)
        return self.decoder(z)

ae = AutoEncoder()

criterion = nn.MSELoss()
optimizer = optim.Adam(ae.parameters(),lr=0.001)

X_tensor = torch.tensor(X_train,dtype=torch.float32)

loss_history = []

for epoch in range(100):
    optimizer.zero_grad()
    recon = ae(X_tensor)
    loss = criterion(recon,X_tensor)
    loss.backward()
    optimizer.step()
    loss_history.append(loss.item())

plt.figure()
plt.plot(loss_history)
plt.title("Autoencoder Loss")
plt.show()

# ============================================
# 6 GA PARAMETERS
# ============================================

population_size = 50
generations = 50
mutation_rate = 0.1

# ============================================
# 7 TESTING
# ============================================

num_tests = 5

results = []
distances_list = []
changes_all = []
probs_before = []
probs_after = []

for i in range(num_tests):

    print("\n====================")
    print("TEST:", i+1)

    x_org = X_test[i].reshape(1,-1)
    y_org = model.predict(x_org)[0]

    #  SAFE CLASS HANDLING
    classes = model.classes_
    y_cf = [c for c in classes if c != y_org][0]

    # Opposite class samples
    X_train_cf = X_train[y_train == y_cf]

    #  FIX EMPTY CASE
    if len(X_train_cf) == 0:
        print(" No opposite class found, using full dataset")
        X_train_cf = X_train

    nbrs = NearestNeighbors(n_neighbors=min(10, len(X_train_cf)))
    nbrs.fit(X_train_cf)

    _,indices = nbrs.kneighbors(x_org)
    neighbors = X_train_cf[indices[0]]

    with torch.no_grad():
        latent_neighbors = ae.encoder(
            torch.tensor(neighbors,dtype=torch.float32)
        )

    prototype = torch.mean(latent_neighbors,dim=0)

    # ============================================
    # LOSS FUNCTIONS (FIXED)
    # ============================================

    def prediction_loss(x):
        prob = model.predict_proba(x.reshape(1,-1))[0]
        class_index = np.where(model.classes_ == y_cf)[0][0]
        return -np.log(prob[class_index] + 1e-6)

    def prototype_loss(x):
        with torch.no_grad():
            z = ae.encoder(torch.tensor(x,dtype=torch.float32))
        return torch.norm(z-prototype).item()

    def distance_loss(x):
        return np.linalg.norm(x - x_org.flatten())

    def fitness(x):
        return prediction_loss(x)+prototype_loss(x)+distance_loss(x)

    # ============================================
    # GENETIC ALGORITHM
    # ============================================

    population = np.random.normal(0,1,
        (population_size, X_train.shape[1]))

    loss_curve = []

    for g in range(generations):

        scores = np.array([fitness(ind) for ind in population])
        loss_curve.append(scores.min())

        best_idx = np.argsort(scores)[:population_size//2]
        survivors = population[best_idx]

        children = []

        while len(children) < population_size:
            p1,p2 = random.sample(list(survivors),2)
            child = (p1+p2)/2

            if random.random() < mutation_rate:
                child += np.random.normal(0,0.1,len(child))

            children.append(child)

        population = np.array(children)

    # Convergence Graph
    plt.figure()
    plt.plot(loss_curve)
    plt.title(f"Convergence Test {i+1}")
    plt.show()

    # ============================================
    # BEST COUNTERFACTUAL
    # ============================================

    scores = np.array([fitness(ind) for ind in population])
    best = population[np.argmin(scores)]

    y_new = model.predict(best.reshape(1,-1))[0]

    print("Original:", y_org)
    print("Counterfactual:", y_new)

    results.append((y_org, y_new))

    distances_list.append(np.linalg.norm(best - x_org.flatten()))
    changes_all.append(best - x_org.flatten())

    probs_before.append(model.predict_proba(x_org)[0][1])
    probs_after.append(model.predict_proba(best.reshape(1,-1))[0][1])

# ============================================
# 8 SUCCESS GRAPH
# ============================================

success = [1 if o!=c else 0 for o,c in results]

plt.figure()
plt.bar(["Success","Failure"],
        [sum(success), len(success)-sum(success)])
plt.title("Success Rate")
plt.show()

# ============================================
# 9 DISTANCE GRAPH
# ============================================

plt.figure()
plt.hist(distances_list, bins=10)
plt.title("Distance Distribution")
plt.show()

# ============================================
# 10 FEATURE IMPORTANCE
# ============================================

avg_change = np.mean(np.abs(changes_all), axis=0)

plt.figure()
plt.bar(range(len(avg_change)), avg_change)
plt.title("Feature Importance")
plt.show()

# ============================================
# 11 PROBABILITY CHANGE
# ============================================

plt.figure()
plt.plot(probs_before, label="Before")
plt.plot(probs_after, label="After")
plt.legend()
plt.title("Probability Change")
plt.show()
