# -*- coding: 5 -*-
"""Test code loan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0LsbomSFkI6JENj8SHmDKKEFn1notK6
"""

# ============================================
# COMPLETE PIPELINE: DATA → TRAIN → SAVE → TEST
# ============================================

import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

# ============================================
# STEP 1: CREATE DUMMY DATASET (1200 ROWS)
# ============================================

np.random.seed(42)
n = 1200

df = pd.DataFrame({
    "Client_Gender": np.random.choice(["Male", "Female"], n),
    "Client_Education": np.random.choice(["Graduate", "Postgraduate"], n),
    "Age": np.random.randint(21, 60, n),
    "Income": np.random.randint(20000, 120000, n),
    "Loan_Amount": np.random.randint(5000, 30000, n),
    "Credit_Score": np.random.randint(550, 800, n),
    "Loan_Term": np.random.choice([24, 36, 48, 60, 72], n)
})

# Target logic
df["Default"] = (
    (df["Credit_Score"] < 620) &
    (df["Income"] < 40000)
).astype(int)

# Save dataset
df.to_csv("loan_default_dataset.csv", index=False)

print(" Dataset Created:", df.shape)

# ============================================
# STEP 2: ENCODING
# ============================================

cat_cols = ["Client_Gender", "Client_Education"]
le_dict = {}

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    le_dict[col] = le

# ============================================
# STEP 3: SPLIT
# ============================================

TARGET = "Default"

X = df.drop(TARGET, axis=1)
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ============================================
# STEP 4: HANDLE IMBALANCE
# ============================================

smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

# ============================================
# STEP 5: TRAIN MODEL
# ============================================

model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train_sm, y_train_sm)

# ============================================
# STEP 6: EVALUATION
# ============================================

y_pred = model.predict(X_test)

print("\n===== MODEL PERFORMANCE =====")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# ============================================
# STEP 7: SAVE MODEL
# ============================================

pickle.dump(model, open("final_xgboost_model.pkl", "wb"))
pickle.dump(le_dict, open("label_encoders.pkl", "wb"))

print("\n Model saved successfully!")

# ============================================
# STEP 8: TESTING ON NEW DATA
# ============================================

print("\n===== TESTING NEW DATA =====")

test_data = pd.DataFrame({
    "Client_Gender": ["Male", "Female", "Male"],
    "Client_Education": ["Graduate", "Postgraduate", "Graduate"],
    "Age": [24, 45, 32],
    "Income": [25000, 90000, 42000],
    "Loan_Amount": [15000, 20000, 18000],
    "Credit_Score": [580, 750, 630],
    "Loan_Term": [36, 60, 48]
})

# Apply encoding
for col in cat_cols:
    test_data[col] = le_dict[col].transform(test_data[col])

# Predict
preds = model.predict(test_data)

print("\n===== PREDICTIONS =====")
for i, p in enumerate(preds):
    print(f"Customer {i+1}: {'DEFAULT' if p==1 else 'NOT DEFAULT'}")

# ============================================
# STEP 9: OPTIONAL GRAPH
# ============================================

cm = confusion_matrix(y_test, y_pred)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.colorbar()

for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i, j], ha='center')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()